baseURL = 'https://haiito92.github.io/Workshop/'
title = "Haiito's Workshop"
theme = "blowfish"

defaultContentLanguage = "fr"

[languages]
  [languages.fr]
    label = "Français"
    weight = 1
    contentDir = "content/fr"
  [languages.en]
    label = "English"
    weight = 2
    contentDir = "content/en"

[outputs]
  home = ["HTML", "RSS", "JSON"]

[params]
  colorScheme = "github"
  enableSearch = true
  smartToC = true
  customCSS = ["css/custom.css"]

  [params.header]
    layout = "floating"

  [params.article]
    showTableOfContents = true
    showPagination = false
    showHero = true
    heroStyle = "background"
    showTags = true

