baseURL = 'https://haiito92.github.io/Workshop/'
title = "Haiito's Workshop"
theme = "blowfish-main"

defaultContentLanguage = "fr"

[languages]
  [languages.fr]
    label = "Français"
    weight = 1
    contentDir = "content/fr"
  [languages.en]
    label = "English"
    weight = 2
    contentDir = "content/en"

[outputs]
  home = ["HTML", "RSS", "JSON"]

[params]
  colorScheme = "fire"
  enableSearch = true

[params.header]
  layout = "floating"
