[[main]]
        name = "Home"
        pageRef = "/"
        weight = 1

    [[main]]
        name = "Projects"
        weight = 2
        identifier = "projects"

        [[main]]
            name = "Personnal"
            pageRef = "/personnal-projects/"
            weight = 1
            identifier = "personnal"
            parent = "projects"

        [[main]]
            name = "School"
            pageRef = "/school-projects/"
            weight = 2
            identifier = "school"
            parent = "projects"

    [[main]]
        name = "Devlogs"
        weight = 4 
        identifier = "devlogs"

        [[main]]
            name = "Little Engine"
            pageRef = "/devlogs/little-engine/"
            weight = 1
            parent = "devlogs"

    [[main]]
        name = "About"
        pageRef = "/about/"
        weight = 5

[[footer]]
    identifier = "github"
    pre = "github"
    url = "https://github.com/Haiito92"
    weight = 1

[[footer]]
    identifier = "linkedin"
    pre = "linkedin"
    url = "https://www.linkedin.com/in/antoine-hanna/"
    weight = 2

[[footer]]
    identifier = "itchio"
    pre = "itchio"
    name = "Itch.io"
    url = "https://haiito.itch.io/"
    weight = 3