[[main]]
        name = "Home"
        pageRef = "/"
        weight = 1

    [[main]]
        name = "Projects"
        weight = 2
        identifier = "projects"

        [[main]]
            name = "Personnal"
            pageRef = "/personnal-projects/"
            weight = 1
            identifier = "personnal"
            parent = "projects"

        [[main]]
            name = "School"
            pageRef = "/school-projects/"
            weight = 2
            identifier = "school"
            parent = "projects"

    [[main]]
        name = "Devlogs"
        weight = 4 
        identifier = "devlogs"

        [[main]]
            name = "Little Engine"
            pageRef = "/devlogs/little-engine/"
            weight = 1
            parent = "devlogs"

    [[main]]
        name = "About"
        pageRef = "/about/"
        weight = 5