baseURL = 'https://haiito92.github.io/Workshop/'
locale = 'en-us'
title = "Haiito's Workshop"
theme = "blowfish-main"

[menu]
    [[menu.main]]
        name = "Home"
        url = "/"
        weight = 1

    [[menu.main]]
        name = "Projects"
        weight = 2
        identifier = "projects"

        [[menu.main]]
            name = "Personnal"
            url = "/personnal-projects/"
            weight = 1
            identifier = "personnal"
            parent = "projects"

        [[menu.main]]
            name = "School"
            url = "/school-projects/"
            weight = 2
            identifier = "school"
            parent = "projects"

    [[menu.main]]
        name = "Devlogs"
        weight = 4 
        identifier = "devlogs"

        [[menu.main]]
            name = "Little Engine"
            url = "/devlogs/little-engine/"
            weight = 1
            parent = "devlogs"

    [[menu.main]]
        name = "About"
        url = "/about/"
        weight = 5

    [[menu.footer]]
        identifier = "github"
        pre = "github"
        url = "https://github.com/Haiito92"
        weight = 1

    [[menu.footer]]
        identifier = "linkedin"
        pre = "linkedin"
        url = "https://www.linkedin.com/in/antoine-hanna/"
        weight = 2

    [[menu.footer]]
        identifier = "itchio"
        pre = "itchio"
        name = "Itch.io"
        url = "https://haiito.itch.io/"
        weight = 3