baseURL = 'https://haiito92.github.io/Workshop/'
locale = 'en-us'
title = "Haiito's Workshop"
theme = "congo"

[menu]
    [[menu.main]]
        name = "Home"
        url = "/"
        weight = 1

    [[menu.main]]
        name = "Personnal Projects"
        url = "/personnal-projects/"
        weight = 2

    [[menu.main]]
        name = "School Projects"
        url = "/school-projects/"
        weight = 3

    [[menu.main]]
        name = "About"
        url = "/about/"
        weight = 4